name: dsh
services:
    deepseek-harness:
        container_name: deepseek-harness
        build:
            context: .
            dockerfile: Dockerfile
            args:
                DEV_TOOLS: admin
        pull_policy: build
        image: deepseek-harness:admin-local
        ports:
            - 3080:3080
        volumes:
            - ./root:/root
        environment:
            - DSH_WORKSPACE=/root/workspace
        restart: unless-stopped
